apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - truenas-external-service/ks.yaml
  - haos-external-service/ks.yaml
  - namespace.yaml
components:
  - ../../components/alerts
