apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: helm-repos
  namespace: flux-system
resources:
  - cilium.yaml
  - csi-driver-nfs.yaml
  - external-dns.yaml
  - kustomization.yaml
  - longhorn.yaml
  - metallb.yaml
  - openebs.yaml
  - truecharts.yaml
  - weave-gitops.yaml
  - traefik.yaml
  - home-ops-mirror.yaml
# more goes here!
